"""
Ontology generation service
Interface 1: Analyze text content and generate entity and relationship type definitions suitable for social simulation
"""

import json
import logging
import re
from typing import Dict, Any, List, Optional
from ..utils.llm_client import LLMClient

logger = logging.getLogger(__name__)


def _to_pascal_case(name: str) -> str:
    """Convert an arbitrary formatted name to PascalCase (e.g. 'works_for' -> 'WorksFor', 'person' -> 'Person'）"""
    # Split by non-alphanumeric characters
    parts = re.split(r'[^a-zA-Z0-9]+', name)
    # Then divide by camelCase boundaries (such as 'camelCase' -> ['camel', 'Case']）
    words = []
    for part in parts:
        words.extend(re.sub(r'([a-z])([A-Z])', r'\1_\2', part).split('_'))
    # Capitalize the first letter of each word, filter empty strings
    result = ''.join(word.capitalize() for word in words if word)
    return result if result else 'Unknown'


# System prompt words generated by ontology
ONTOLOGY_SYSTEM_PROMPT = """You are a professional knowledge graph ontology design expert. Your task is to analyze the given text content and simulation requirements and design a suitable**Social media public opinion simulation**Entity types and relationship types。

**IMPORTANT: You must output valid JSON formatted data, do not output anything else。**

## Core mission background

we are building a**Social media public opinion simulation system**。in this system：
- Every entity is a person who can speak, interact, and spread information on social media"account"or"main body"
- Entities will influence, forward, comment, and respond to each other
- We need to simulate the reactions of all parties and information dissemination paths in public opinion events

Therefore，**The entity must be a real entity that exists in reality and can speak and interact on social media.**：

**can be**：
- Specific individuals (public figures, parties, opinion leaders, experts and scholars, ordinary people）
- Companies and enterprises (including their official accounts)）
- Organizational institutions (universities, associations, NGOs, trade unions, etc.）
- Government departments, regulatory agencies
- Media organizations (newspapers, TV stations, self-media, websites）
- The social media platform itself
- Representatives of specific groups (such as alumni associations, fan groups, rights protection groups, etc.）

**cannot be**：
- abstract concepts (such as"public opinion"、"mood"、"trend"）
- theme/topic (such as"academic integrity"、"education reform"）
- point of view/attitude (such as"Supporters"、"Opposition"）

## Output format

Please output JSON format, including the following structure：

```json
{
    "entity_types": [
        {
            "name": "Entity type name (English，PascalCase）",
            "description": "Short description (English, no more than 100 characters）",
            "attributes": [
                {
                    "name": "Attribute name (English，snake_case）",
                    "type": "text",
                    "description": "Property description"
                }
            ],
            "examples": ["Example entity1", "Example entity2"]
        }
    ],
    "edge_types": [
        {
            "name": "Relationship type name (English，UPPER_SNAKE_CASE）",
            "description": "Short description (English, no more than 100 characters）",
            "source_targets": [
                {"source": "Source entity type", "target": "target entity type"}
            ],
            "attributes": []
        }
    ],
    "analysis_summary": "A brief analysis of the content of the text (Chinese）"
}
```

## Design Guidelines (extremely important！）

### 1. Entity type design - must be strictly observed

**Quantity requirement: There must be exactly 10 entity types**

**Hierarchy requirements (must contain both concrete and abstract types）**：

Your 10 entity types must contain the following levels：

A. **Cover type (must be included, placed in the last 2 items in the list）**：
   - `Person`: The cover-up type of any natural person. A person is classified into this category when he or she does not fit into any of the other more specific person types.。
   - `Organization`: The go-to type for any organization. An organization is classified into this category when it does not belong to another more specific organization type。

B. **Specific types (8, designed according to text content）**：
   - Design more specific types for the main characters that appear in the text
   - For example: if the text involves an academic event, there could be `Student`, `Professor`, `University`
   - For example: if the text relates to a business event, there could be `Company`, `CEO`, `Employee`

**Why do you need a cover-up type?**：
- Various characters appear in the text, such as"Primary and secondary school teachers"、"Passerby"、"A certain netizen"
- If there is no specific type matching, they should be classified under `Person`
- In the same way, small organizations, temporary groups, etc. should be classified as `Organization`

**Type-specific design principles**：
- Identify frequently occurring or key character types from text
- Each concrete type should have clear boundaries to avoid overlap
- description The difference between this type and the cover-up type must be clearly stated

### 2. Relationship type design

- quantity：6-10indivual
- Relationships should reflect real connections in social media interactions
- to ensure a relationship source_targets Covers the entity types you define

### 3. Attribute design

- each entity type1-3key attributes
- **Notice**：Property name cannot be used `name`、`uuid`、`group_id`、`created_at`、`summary`（These are system reserved words）
- Recommended：`full_name`, `title`, `role`, `position`, `location`, `description` wait

## Entity type reference

**Personal category (specific）**：
- Student: student
- Professor: professor/scholar
- Journalist: reporter
- Celebrity: star/internet celebrity
- Executive: executive
- Official: government officials
- Lawyer: lawyer
- Doctor: doctor

**Personal category）**：
- Person: Any natural person (used when not falling into the specific categories above）

**Organization type (specific）**：
- University: College
- Company: company enterprise
- GovernmentAgency: government agencies
- MediaOutlet: media organization
- Hospital: Hospital
- School: Primary and secondary schools
- NGO: non-governmental organization

**Organization type (cover the bottom line)）**：
- Organization: Any organization (used when not one of the specific types listed above）

## Relationship type reference

- WORKS_FOR: working on
- STUDIES_AT: Studied at
- AFFILIATED_WITH: Belong to
- REPRESENTS: represent
- REGULATES: supervision
- REPORTS_ON: report
- COMMENTS_ON: Comment
- RESPONDS_TO: respond
- SUPPORTS: support
- OPPOSES: be opposed to
- COLLABORATES_WITH: cooperate
- COMPETES_WITH: compete
"""


class OntologyGenerator:
    """
    ontology generator
    Analyze text content and generate entity and relationship type definitions
    """
    
    def __init__(self, llm_client: Optional[LLMClient] = None):
        self.llm_client = llm_client or LLMClient()
    
    def generate(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate ontology definition
        
        Args:
            document_texts: Document text list
            simulation_requirement: Simulation requirement description
            additional_context: extra context
            
        Returns:
            ontology definition（entity_types, edge_typeswait）
        """
        # Build user messages
        user_message = self._build_user_message(
            document_texts, 
            simulation_requirement,
            additional_context
        )
        
        messages = [
            {"role": "system", "content": ONTOLOGY_SYSTEM_PROMPT},
            {"role": "user", "content": user_message}
        ]
        
        # callLLM
        result = self.llm_client.chat_json(
            messages=messages,
            temperature=0.3,
            max_tokens=4096
        )
        
        # Validation and post-processing
        result = self._validate_and_process(result)
        
        return result
    
    # The maximum length of text passed to LLM (50,000 words）
    MAX_TEXT_LENGTH_FOR_LLM = 50000
    
    def _build_user_message(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str]
    ) -> str:
        """Build user messages"""
        
        # Merge text
        combined_text = "\n\n---\n\n".join(document_texts)
        original_length = len(combined_text)
        
        # If the text exceeds 50,000 words, it will be truncated (only affects the content passed to LLM, not the graph construction)）
        if len(combined_text) > self.MAX_TEXT_LENGTH_FOR_LLM:
            combined_text = combined_text[:self.MAX_TEXT_LENGTH_FOR_LLM]
            combined_text += f"\n\n...(Total original text{original_length}words, before interception{self.MAX_TEXT_LENGTH_FOR_LLM}Words used for ontology analysis)..."
        
        message = f"""## Simulation requirements

{simulation_requirement}

## Document content

{combined_text}
"""
        
        if additional_context:
            message += f"""
## Additional instructions

{additional_context}
"""
        
        message += """
Please design entity types and relationship types suitable for social public opinion simulation based on the above content.。

**rules that must be followed**：
1. Exactly 10 entity types must be output
2. The last two must be disclosure types: Person (personal disclosure) and Organization (organization disclosure)）
3. The first 8 are specific types designed based on text content
4. All entity types must be subjects that can speak in reality and cannot be abstract concepts.
5. Property name cannot be used name、uuid、group_id Wait for reserved words, use full_name、org_name Wait for replacement
"""
        
        return message
    
    def _validate_and_process(self, result: Dict[str, Any]) -> Dict[str, Any]:
        """Validation and post-processing results"""
        
        # Make sure required fields exist
        if "entity_types" not in result:
            result["entity_types"] = []
        if "edge_types" not in result:
            result["edge_types"] = []
        if "analysis_summary" not in result:
            result["analysis_summary"] = ""
        
        # Validate entity type
        # Record the mapping of the original name to PascalCase for subsequent correction of edge source_targets Quote
        entity_name_map = {}
        for entity in result["entity_types"]:
            # Force conversion of entity name to PascalCase (required by Zep API）
            if "name" in entity:
                original_name = entity["name"]
                entity["name"] = _to_pascal_case(original_name)
                if entity["name"] != original_name:
                    logger.warning(f"Entity type name '{original_name}' auto-converted to '{entity['name']}'")
                entity_name_map[original_name] = entity["name"]
            if "attributes" not in entity:
                entity["attributes"] = []
            if "examples" not in entity:
                entity["examples"] = []
            # Make sure the description does not exceed 100 characters
            if len(entity.get("description", "")) > 100:
                entity["description"] = entity["description"][:97] + "..."
        
        # Verify relationship type
        for edge in result["edge_types"]:
            # Force the edge name to be converted to SCREAMING_SNAKE_CASE（Zep API Require）
            if "name" in edge:
                original_name = edge["name"]
                edge["name"] = original_name.upper()
                if edge["name"] != original_name:
                    logger.warning(f"Edge type name '{original_name}' auto-converted to '{edge['name']}'")
            # Correction source_targets Entity name references in , consistent with converted PascalCase
            for st in edge.get("source_targets", []):
                if st.get("source") in entity_name_map:
                    st["source"] = entity_name_map[st["source"]]
                if st.get("target") in entity_name_map:
                    st["target"] = entity_name_map[st["target"]]
            if "source_targets" not in edge:
                edge["source_targets"] = []
            if "attributes" not in edge:
                edge["attributes"] = []
            if len(edge.get("description", "")) > 100:
                edge["description"] = edge["description"][:97] + "..."
        
        # Zep API Limitations: Maximum 10 custom entity types, maximum 10 custom edge types
        MAX_ENTITY_TYPES = 10
        MAX_EDGE_TYPES = 10

        # Remove duplicates: Press name to remove duplicates and keep the first occurrence.
        seen_names = set()
        deduped = []
        for entity in result["entity_types"]:
            name = entity.get("name", "")
            if name and name not in seen_names:
                seen_names.add(name)
                deduped.append(entity)
            elif name in seen_names:
                logger.warning(f"Duplicate entity type '{name}' removed during validation")
        result["entity_types"] = deduped

        # Backpack type definition
        person_fallback = {
            "name": "Person",
            "description": "Any individual person not fitting other specific person types.",
            "attributes": [
                {"name": "full_name", "type": "text", "description": "Full name of the person"},
                {"name": "role", "type": "text", "description": "Role or occupation"}
            ],
            "examples": ["ordinary citizen", "anonymous netizen"]
        }
        
        organization_fallback = {
            "name": "Organization",
            "description": "Any organization not fitting other specific organization types.",
            "attributes": [
                {"name": "org_name", "type": "text", "description": "Name of the organization"},
                {"name": "org_type", "type": "text", "description": "Type of organization"}
            ],
            "examples": ["small business", "community group"]
        }
        
        # Check if there is already a pocket type
        entity_names = {e["name"] for e in result["entity_types"]}
        has_person = "Person" in entity_names
        has_organization = "Organization" in entity_names
        
        # The type of cover that needs to be added
        fallbacks_to_add = []
        if not has_person:
            fallbacks_to_add.append(person_fallback)
        if not has_organization:
            fallbacks_to_add.append(organization_fallback)
        
        if fallbacks_to_add:
            current_count = len(result["entity_types"])
            needed_slots = len(fallbacks_to_add)
            
            # If there will be more than 10 after adding, some existing types need to be removed
            if current_count + needed_slots > MAX_ENTITY_TYPES:
                # Calculate how many need to be removed
                to_remove = current_count + needed_slots - MAX_ENTITY_TYPES
                # Removed from the end (retaining the more important concrete types at the front）
                result["entity_types"] = result["entity_types"][:-to_remove]
            
            # Add cover type
            result["entity_types"].extend(fallbacks_to_add)
        
        # Ultimately ensuring that limits are not exceeded (defensive programming）
        if len(result["entity_types"]) > MAX_ENTITY_TYPES:
            result["entity_types"] = result["entity_types"][:MAX_ENTITY_TYPES]
        
        if len(result["edge_types"]) > MAX_EDGE_TYPES:
            result["edge_types"] = result["edge_types"][:MAX_EDGE_TYPES]
        
        return result
    
    def generate_python_code(self, ontology: Dict[str, Any]) -> str:
        """
        Convert ontology definitions into Python code (something likeontology.py）
        
        Args:
            ontology: ontology definition
            
        Returns:
            Pythoncode string
        """
        code_lines = [
            '"""',
            'Custom entity type definition',
            'Automatically generated by MiroFish for social opinion simulation',
            '"""',
            '',
            'from pydantic import Field',
            'from zep_cloud.external_clients.ontology import EntityModel, EntityText, EdgeModel',
            '',
            '',
            '# ============== Entity type definition ==============',
            '',
        ]
        
        # Generate entity type
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            desc = entity.get("description", f"A {name} entity.")
            
            code_lines.append(f'class {name}(EntityModel):')
            code_lines.append(f'    """{desc}"""')
            
            attrs = entity.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')
            
            code_lines.append('')
            code_lines.append('')
        
        code_lines.append('# ============== Relationship type definition ==============')
        code_lines.append('')
        
        # Generate relationship type
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            # Convert to PascalCase class name
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            desc = edge.get("description", f"A {name} relationship.")
            
            code_lines.append(f'class {class_name}(EdgeModel):')
            code_lines.append(f'    """{desc}"""')
            
            attrs = edge.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')
            
            code_lines.append('')
            code_lines.append('')
        
        # Generate type dictionary
        code_lines.append('# ============== Type configuration ==============')
        code_lines.append('')
        code_lines.append('ENTITY_TYPES = {')
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            code_lines.append(f'    "{name}": {name},')
        code_lines.append('}')
        code_lines.append('')
        code_lines.append('EDGE_TYPES = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            code_lines.append(f'    "{name}": {class_name},')
        code_lines.append('}')
        code_lines.append('')
        
        # generating edgessource_targetsmapping
        code_lines.append('EDGE_SOURCE_TARGETS = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            source_targets = edge.get("source_targets", [])
            if source_targets:
                st_list = ', '.join([
                    f'{{"source": "{st.get("source", "Entity")}", "target": "{st.get("target", "Entity")}"}}'
                    for st in source_targets
                ])
                code_lines.append(f'    "{name}": [{st_list}],')
        code_lines.append('}')
        
        return '\n'.join(code_lines)

